import { StyleSheet } from "react-native";

export const colors = {
    background: '#121212',
    primary: '#198F8D',
    card: '#1E1E1E',
    text: '#FFFFFF',
    yellow: "#D4A017",
    yellowDark: "#B98C00",
    gray: '#A0A0A0',
    danger: '#D93F3F',
    border: '#333',
};

export const spacing = {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
};

export const fonts = {
    regular: 'System',
    bold: 'System',
    size: {
        sm: 12,
        md: 16,
        lg: 20,
        xl: 24,
        xxl: 28,
    },
};

export const theme = StyleSheet.create({
    screenContainer: {
        flex: 1,
        position: "relative",
        backgroundColor: colors.background,
        paddingTop: spacing.lg,
        paddingBottom: 70,
        width: '100%',
        maxWidth: '100%',
        overflow: 'hidden',
    },
    title: {
        textAlign: 'center',
        fontSize: fonts.size.xxl,
        fontWeight: 'bold',
        color: colors.text,
    },
    headerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
    },
    addButton: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    addButtonText: {
        color: colors.text,
        fontSize: 24,
        fontWeight: '300',
        textAlign: 'center',
        lineHeight: 36,
    },
    label: {
        color: colors.text,
        fontSize: fonts.size.md,
        fontWeight: 'bold',
        marginTop: spacing.lg,
        marginBottom: spacing.sm,
    },
    input: {
        width: "100%",
        height: 48,
        backgroundColor: "#222",
        borderRadius: 12,
        paddingHorizontal: 14,
        marginTop: 12,
        borderWidth: 1,
        borderColor: colors.border,
        color: colors.text,
        fontSize: 16,
    },
    previewImage: {
        width: '100%',
        height: 200,
        borderRadius: 10,
        marginTop: spacing.md,
        resizeMode: 'cover',
    },
    publishButton: {
        backgroundColor: colors.primary,
        padding: spacing.lg,
        borderRadius: 10,
        alignItems: 'center',
        marginTop: spacing.xl,
        marginBottom: spacing.xl,
    },
    publishButtonText: {
        color: colors.text,
        fontSize: fonts.size.lg,
        fontWeight: 'bold',
    },
    profileButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        overflow: "hidden",
    },
    profileImage: {
        width: "100%",
        height: "100%",
        borderRadius: 20,
    },
    profileImageLarge: {
        width: 160,
        height: 160,
        borderRadius: 80,
        borderWidth: 3,
    },
    profileName: {
        color: colors.text,
        fontSize: fonts.size.xxl,
        fontWeight: "bold",
    },
    divider: {
        height: 1,
        backgroundColor: "rgba(255, 255, 255, 0.15)",
        width: "100%",
        marginTop: 10,
        marginBottom: 10,
    },
    registerBox: {
        width: "100%",
        maxWidth: 380,
        backgroundColor: colors.card,
        borderRadius: 22,
        padding: 25,
        paddingTop: 35,
        boxShadow: "0px 4px 14px rgba(0,0,0,0.45)",
        alignItems: "center",
    },
    birthRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        width: "100%",
        marginTop: 10,
    },
    birthPicker: {
        flex: 1,
        height: 48,
        backgroundColor: "#222",
        borderRadius: 12,
        marginHorizontal: 4,
        borderWidth: 1,
        borderColor: colors.border,
        color: colors.text,
    },
    button: {
        width: "100%",
        backgroundColor: colors.yellow,
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
        marginTop: 18,
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 5,
    },
    buttonText: {
        color: "#000",
        fontSize: 17,
        fontWeight: "700",
    },
    link: {
        marginTop: 14,
        color: colors.yellow,
        fontSize: 15,
    },
    bottomRow: {
        flexDirection: "row",
        justifyContent: "space-around",
        alignItems: "center",
        position: "absolute",
        bottom: 0,
        left: 0,
        right: 0,
        paddingVertical: 12,
        paddingHorizontal: 10,
        backgroundColor: colors.background,
        borderTopWidth: 1,
        borderTopColor: '#333',
    },
});
