@startuml
title Storyboard - Application mobile KAEB (StudyShare)

left to right direction 
hide circle

rectangle "Login" as Login
rectangle "Register" as Register
rectangle "Home" as Home
rectangle "Profile" as Profile
rectangle "Communaute" as Communaute
rectangle "Publication" as Publication
rectangle "CreatePost" as CreatePost
rectangle "FocusRoom" as FocusRoom
rectangle "HabitTracker" as HabitTracker
rectangle "LockIn" as LockIn
rectangle "Recherche" as Recherche

rectangle "Liste des taches" as ListeTaches
rectangle "Ajouter une tache" as AjouterTache
rectangle "Modifier une tache" as ModifierTache
rectangle "Supprimer une tache" as SupprimerTache
rectangle "Consulter une tache" as ConsulterTache

rectangle "Liste des posts" as ListePosts
rectangle "Ajouter post" as AjouterPost
rectangle "Modifier post" as ModifierPost
rectangle "Supprimer post" as SupprimerPost
rectangle "Consulter post" as ConsulterPost

' Authentification
Login --> Home : connexion réussie
Login <. Home : déconnexion
Login --> Register : créer un compte
Login <. Register : retour

' Profil
Home --> Profile : voir profil
Profile --> Home : retour

' Navigation principale
Home --> Communaute : entrer dans une communauté
Home --> Publication : voir publications
Home --> FocusRoom : mode focus
Home --> HabitTracker : suivi d'habitudes
Home --> LockIn : activer Lock-In
Home --> Recherche : rechercher contenu

' CRUDL CreatePost
Home --> CreatePost : bouton "+"
CreatePost --> AjouterPost : créer un post
CreatePost --> ModifierPost : modifier un post
CreatePost --> SupprimerPost : supprimer un post
CreatePost --> ConsulterPost : voir post
CreatePost --> ListePosts : Liste de posts a l'utilisateur
ListePosts .> CreatePost : retour
AjouterPost .> CreatePost : retour
ModifierPost .> CreatePost : retour
SupprimerPost .> CreatePost : retour
ConsulterPost .> CreatePost : retour
CreatePost --> Home : retour (annuler)
CreatePost --> Home : confirmer post (sauvegarde réussie)

HabitTracker --> ListeTaches : liste des tâches
ListeTaches --> AjouterTache : ajouter
ListeTaches --> ModifierTache : modifier
ListeTaches --> SupprimerTache : supprimer
ListeTaches --> ConsulterTache : consulter
AjouterTache .> ListeTaches : retour
ModifierTache .> ListeTaches : retour
SupprimerTache .> ListeTaches : retour
ConsulterTache .> ListeTaches : retour
ListeTaches --> HabitTracker : retour
HabitTracker --> Home : retour


